# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60f1591ef253602a6c83f4f3bb796949f8f708bf48233c719423fb0011a2f63e54a123188a34101ba823cd55ae2b997cb65ab99f4613bb267f97d16509ae4ab7

test:
  secret_key_base: 78a25a0dfb28b3588d352a76d46be5a0f1d589a933cec7338a0bd57e416ced9a0a831c103468c04d97b398077180bd02e22fb6aeb48fcb3e18971eff1c69e0aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
